name: Bug Report
description: Report a bug in shadcn-ui-rs
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Run `shadcn-ui add button`
        2. Build with `cargo build`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.93.0"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: shadcn-ui-rs Version
      description: Output of `shadcn-ui --version`
      placeholder: "0.1.0"
    validations:
      required: true
